itest:
  build: docker/itest
  links:
    - kafka
    - zookeeper
  volumes:
    - .:/work
  command: echo "dummy command"

kafka:
  build: docker/kafka
  expose:
    - "9092"
  links:
    - zookeeper

zookeeper:
  build: docker/zookeeper
  expose:
    - "2181"
